# Generated by Django 4.2.7 on 2025-09-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_currency', models.CharField(blank=True, default='EUR', max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='receipts/')),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('amount_in_target_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Dining Out', 'Dining Out'), ('Healthcare', 'Healthcare'), ('Debt Payments', 'Debt Payments'), ('Insurance', 'Insurance'), ('Clothing', 'Clothing'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Childcare', 'Childcare'), ('Pet Care', 'Pet Care'), ('Subscriptions', 'Subscriptions'), ('Miscellaneous', 'Miscellaneous')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
